### PR TITLE
fix(style): header avoid scroll

### PR DESCRIPTION
**Pull request by Haroenv**
# settings

## Before 

screenshot 2018-11-28 at 15 46 56

## After

screenshot 2018-11-28 at 15 47 00

# ask HN

## Before
screenshot 2018-11-28 at 15 47 12

## After

screenshot 2018-11-28 at 15 47 22

### CODE REVIEW

**Comment by Haroenv** [comment]
@pixelastic do you also know how to deploy this?

**Comment by pixelastic** [comment]
Nope. I would think it automatically deploys, but I'm not sure. @redox might know (we should document it)

**Comment by redox** [comment]
> Nope. I would think it automatically deploys, but I'm not sure. @redox might know (we should document it)

Deploying now, still manual process.

**Comment by pixelastic** [comment]
@redox Could you let us know how it's done so we can document it and have more people able to deploy?

**Comment by redox** [comment]
> @redox Could you let us know how it's done so we can document it and have more people able to deploy?

Done.

To deploy, we're using capistrano and therefore you need SSH access to the underlying machines and run from your own computer:

```sh
$ bundle exec cap deploy
```

since a few releases, the `bluepill` is kinda failing to restart and therefore stop the deployment, so you need to force the restart with:

```sh
$ bundle exec cap deploy:restart
```

**Comment by pixelastic** [comment]
Added a PR with the documentation: https://github.com/algolia/hn-search/pull/132

**Pull request merged**
